Log the payload of the triggered event.
altipla-consulting/directus-call-go pull request #5
Opened 2024-10-23 07:02 UTC by pkb-code

2024-10-23 07:25 UTC, ernestoalejo requested changes
Log continuos no, porque va a superar el máximo de línea de Docker y no lo podemos por tanto exportar bien a los productos de Google y Azure; mandarlo a Sentry cuando haya errores solamente.

2024-10-23 09:24 UTC, pkb-code commented
corregido.

2024-10-23 12:08 UTC, ernestoalejo requested changes
Sentry, por consola no, Sentry. Para que llegue como body cuando lo necesitamos depurar:

![image](https://github.com/user-attachments/assets/9e775eb9-63b9-4d1d-a2c3-5a106deb1c11)

2024-11-04 23:08 UTC, ernestoalejo reviewed
Esto tampoco manda el body como tal. Lo he implementado por separado.

2024-11-04 23:08 UTC, closed without merging